### ISSUE TITLE
[Clean code] 缺少函数TreePredictParser, SpanPredictParser, RTRolePredictParser

### ISSUE THREAD

**Issue by waow123** [boy56/GDAP#1]
你好，我在运行run_tri_predict.bash的时候报错，检查之后发现evaluation.py这个文件的第9行
from extraction.predict_parser.target_predict_parser import TreePredictParser, SpanPredictParser, RTRolePredictParser, RolePredictParser, TriPredictParser
导入时提示缺少函数TreePredictParser, SpanPredictParser, RTRolePredictParser
![1635586363(1)](https://user-images.githubusercontent.com/33931444/139527764-d28d6deb-1152-4783-8ddf-54518c4d7e41.png)
我查找之后发现，在target_predict_parser.py这个文件中并没有这几个函数

**Comment by boy56** [comment]
> 你好，我在运行run_tri_predict.bash的时候报错，检查之后发现evaluation.py这个文件的第9行 from extraction.predict_parser.target_predict_parser import TreePredictParser, SpanPredictParser, RTRolePredictParser, RolePredictParser, TriPredictParser 导入时提示缺少函数TreePredictParser, SpanPredictParser, RTRolePredictParser ![1635586363(1)](https://user-images.githubusercontent.com/33931444/139527764-d28d6deb-1152-4783-8ddf-54518c4d7e41.png) 我查找之后发现，在target_predict_parser.py这个文件中并没有这几个函数

你好，感谢指出相关问题！这几个类在论文中的方法里面暂时并不需要，属于代码整理时候的疏漏，相关的行数删掉就好了，目前已经做了更新。建议先训练模型，模型中的运行log会有各个阶段独立的评估，整体的评估(et识别 + tri/role抽取) 再采用predict脚本的形式。后续仍有问题欢迎继续提出！

**Comment by Pzoom522** [comment]
Please feel to reopen this issue upon further questions : )
