### ISSUE TITLE
Wrong arguments for the ET task.

### ISSUE THREAD

**Issue by littlefive5** [boy56/GDAP#2]
https://github.com/RingBDStack/GDAP/blob/main/README.md#training
The script to train the et model is wrong. The argument format should be `et` not `tri`. The `tri` would gave poor performance.

**Comment by boy56** [comment]
> https://github.com/RingBDStack/GDAP/blob/main/README.md#training The script to train the et model is wrong. The argument format should be `et` not `tri`. The `tri` would gave poor performance.

Thanks for your attention! We made a mistake here and we'll revise it soon.

**Comment by Pzoom522** [comment]
Closed as solved. Please feel free to reopen this issue upon further questions : )
