### ISSUE TITLE
可以公布一下关于Trigger和Argument的identification准确率嘛

### ISSUE THREAD

**Issue by ChesterXi** [boy56/GDAP#3]

**Comment by boy56** [comment]
> _No description provided._

因为我们的方案主要采用的是 类型(role-type)作为prompt信息来对论元(argument)进行生成的方式，所以trigger和argument在生成出来的时候，就已经带有了对应的类型信息，因此没有再单独去统计identification的相关指标(该类指标对本模型的参考意义不大)。

**Comment by Pzoom522** [comment]
Please feel free to reopen this issue upon further needs.
