### ISSUE TITLE
Event type extraction inference

### ISSUE THREAD

**Issue by AndDoIt** [boy56/GDAP#4]
I have finished the training of Entity type extraction task, and I have a file with raw text and no event label, I wondered how to get the entity type inference?

**Comment by boy56** [comment]
Entity type extraction? Is it like Argument Extraction?   
Well, In the inference process, you can do 
(1) Use a classification model(ours or other methods like bert) to get the event types of the raw text
(2) Take the event type, role type(related to the event type) and the raw text as the input, and the model will generate the arguments(or entities) of this role type.

**Comment by AndDoIt** [comment]
Thanks very much for your reply!
I just finished the model training of first module of Event Type Dection, and now I want to use your model that I have trained to get the event types of the raw text. While the other two tasks have the inference bash script, for my first task, what kind of format that dataset shoule be converted? And just use run_seq2seq.py with argument --do_predict?

**Comment by boy56** [comment]
> Thanks very much for your reply! I just finished the model training of first module of Event Type Dection, and now I want to use your model that I have trained to get the event types of the raw text. While the other two tasks have the inference bash script, for my first task, what kind of format that dataset shoule be converted? And just use run_seq2seq.py with argument --do_predict?

I recommend you that:
(1) use the data_convert/convert_text_to_target.py to convert the data format.
(2) train the argument extraction model use the gold event type (_bash run_seq2seq_span.bash_ XXX).
(3) use the argument extraction model to do this task: _event type</s> role type</s> raw text  -> roles_. (_run_arg_predict.bash_ will be useful).

**Comment by AndDoIt** [comment]
Okay, I see. Thanks for your kindly reply!
