### ISSUE TITLE
请问模型可以解决句子中存在多个同一事件的情况吗？

### ISSUE THREAD

**Issue by npq567** [boy56/GDAP#5]
感谢作者的贡献给我很多帮助，这里有一个问题：假如某句话中有两个ATTACK事件，ETD模型的解码结果是 ((ATTACK)(ATTACK))这样吗，还是只解码一个ATTACK，TrgE，ArgE解码结果没有想象到。希望作者能够解答我的疑问

**Comment by boy56** [comment]
> 感谢作者的贡献给我很多帮助，这里有一个问题：假如某句话中有两个ATTACK事件，ETD模型的解码结果是 ((ATTACK)(ATTACK))这样吗，还是只解码一个ATTACK，TrgE，ArgE解码结果没有想象到。希望作者能够解答我的疑问

1. 根据当前建模方法的限制的话，目前是只解码一个ATTACK，然后根据ATTACK去生成所有的Trigger和Role(能够区分句子中不同事件类型的多事件，处理不了同一个事件类型的多事件)。 
2. 一个可能的解决方案就是，将类型ET识别出来后，去生成所有的Trigger，然后 用 ET+Tri 作为事件的唯一Prompt 去做Role的生成 (处理不了触发词与事件类型都相同的多事件)。
3. 目前研究里面，ACE05的评估以及相关比赛的评估大多都是按照(ET，RT, Role)的方法进行论元的评估，很少以“事件”作为一个计算单位进行评估的，因为有点太难了。

**Comment by npq567** [comment]
感谢您的回答，谢谢
