### ISSUE TITLE
关于约束解码的一个问题

### ISSUE THREAD

**Issue by hlee-top** [boy56/GDAP#6]
作者您好，关于约束解码我有一个问题，请问constraint_decoder为什么只在下面代码条件下使用，希望作者能够解答我的疑问，谢谢！

https://github.com/RingBDStack/GDAP/blob/f6acafafd473cd1ccb57d79aaf95be14de7646fd/seq2seq/constrained_seq2seq.py#L145-L152

**Comment by boy56** [comment]
> 作者您好，关于约束解码我有一个问题，请问constraint_decoder为什么只在下面代码条件下使用，希望作者能够解答我的疑问，谢谢！
> 
> https://github.com/RingBDStack/GDAP/blob/f6acafafd473cd1ccb57d79aaf95be14de7646fd/seq2seq/constrained_seq2seq.py#L145-L152

这个就是在预测生成的时候使用一个约束解码，训练过程中是不参与的。

**Comment by hlee-top** [comment]
感谢您的回答
