### ISSUE TITLE
与pipeline模型的比较和改进

### ISSUE THREAD

**Issue by BudBudding** [boy56/GDAP#7]
您好，你的工作中提到 将文本首先经过Event Type Detection，再进行Trigge和Argument Extractions的抽取。在joint模型提出来的时候，指出pipeline模型因为首先判断了事件类型，如果事件类型错误就会导致后面Argument 的抽取发生错误。请问您的工作中，与pipeline模型有什么不同，是否还是存在事件类型判断错误 导致后面的工作没有意义的问题？

**Comment by boy56** [comment]
> 您好，你的工作中提到 将文本首先经过Event Type Detection，再进行Trigge和Argument Extractions的抽取。在joint模型提出来的时候，指出pipeline模型因为首先判断了事件类型，如果事件类型错误就会导致后面Argument 的抽取发生错误。请问您的工作中，与pipeline模型有什么不同，是否还是存在事件类型判断错误 导致后面的工作没有意义的问题？

这篇工作本质也是pipeline的形式，这种误差传递只能缓解，不能消除。joint形式的模型，需要看建模方法&解码输出的构造，有些形式可以在理论上消除误差传递，但最终的效果又会受到其它方面的影响(例如ET-RT组合的NER方法，标签过多导致的效果下降)。最终还是看在数据集上的实验效果，以实际适用的数据和场景灵活变动比较好。

**Comment by BudBudding** [comment]
十分感谢您的回答。我按照您这边提供的readme，跳转到了dygiepp的数据处理部分，“bash ./scripts/data/ace-event/collect_ace_event.sh [path-to-ACE-data].”，这里的“path-to-ACE-data”是指ACE2005原数据集的存放路径吗？
