### ISSUE TITLE
event.schema

### ISSUE THREAD

**Issue by BudBudding** [boy56/GDAP#8]
您好，我按照您所说的 进行了数据的预处理，但是 我得到的结果只有train/val/test.json，没有生成event.schema。请问这个是自己手动添加的吗？如果不是，是以什么样的方式获得的，希望得到您的分享和帮助

**Comment by boy56** [comment]
> 您好，我按照您所说的 进行了数据的预处理，但是 我得到的结果只有train/val/test.json，没有生成event.schema。请问这个是自己手动添加的吗？如果不是，是以什么样的方式获得的，希望得到您的分享和帮助

convert_text_to_target.py 这个文件的83行附近是处理schema然后导出为文件的逻辑，你可以打印一下log看看是啥原因没生成出来。

**Comment by BudBudding** [comment]
谢谢您的帮助和分享。我已经成功的得到了完整的数据！十分感谢
